WARNING: leap-second auto-update failed due to the following exception: RuntimeError('Cache is locked after 5.05 s. This may indicate an astropy bug or that kill -9 was used. If you want to unlock the cache remove the directory /home/data/bl407/jwiniarczyk/.astropy/cache/download/py3/lock. Lock claims to be held by process 6608.',) [astropy.time.core]
The chain is shorter than 50 times the integrated autocorrelation time for 10 parameter(s). Use this estimate with caution and run a longer chain!
N/50 = 6;
tau: [33.61310608 31.5658363  30.59091719 32.82978602 34.47721611 26.56784035
 26.97703222 36.1996007  37.54530902 28.09371685]
